# Generated by Django 3.0.3 on 2020-06-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('genre', models.TextField()),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('avg_polarity', models.FloatField(blank=True, null=True)),
                ('avg_stars', models.FloatField(blank=True, null=True)),
                ('actors_score', models.FloatField(blank=True, null=True)),
                ('story_score', models.FloatField(blank=True, null=True)),
                ('characters_score', models.FloatField(blank=True, null=True)),
                ('audio_video_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('language', models.TextField()),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('movie_series', models.BooleanField(blank=True, null=True)),
                ('original_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('critic', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('freshness', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('analyzed', models.BooleanField()),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosNeg',
            fields=[
                ('predicted_value', models.FloatField(blank=True, null=True)),
                ('predicted_class', models.TextField(blank=True, null=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='reviewjoin', serialize=False, to='movies.Reviews')),
                ('stat_used', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pos_neg',
                'managed': False,
            },
        ),
    ]
