# Generated by Django 3.0.3 on 2020-06-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspects',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movies.Reviews')),
                ('actor_pos', models.IntegerField(blank=True, null=True)),
                ('actor_neg', models.IntegerField(blank=True, null=True)),
                ('audio_video_pos', models.IntegerField(blank=True, null=True)),
                ('audio_video_neg', models.IntegerField(blank=True, null=True)),
                ('character_pos', models.IntegerField(blank=True, null=True)),
                ('character_neg', models.IntegerField(blank=True, null=True)),
                ('experience_pos', models.IntegerField(blank=True, null=True)),
                ('experience_neg', models.IntegerField(blank=True, null=True)),
                ('story_pos', models.IntegerField(blank=True, null=True)),
                ('story_neg', models.IntegerField(blank=True, null=True)),
                ('stat_used', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aspects',
                'managed': False,
            },
        ),
    ]
