# Generated by Django 3.0.3 on 2020-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('critic', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('freshness', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCsfd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField(blank=True, null=True)),
                ('critic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_csfd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersFdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField(blank=True, null=True)),
                ('critic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_fdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersImdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField(blank=True, null=True)),
                ('critic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_imdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersRottentomatoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField(blank=True, null=True)),
                ('critic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_rottentomatoes',
                'managed': False,
            },
        ),
    ]
