# Generated by Django 3.0.3 on 2020-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('num_pos', models.IntegerField(blank=True, null=True)),
                ('num_neg', models.IntegerField(blank=True, null=True)),
                ('avg_stars', models.FloatField()),
                ('actors_score', models.IntegerField()),
                ('story_score', models.IntegerField()),
                ('characters_score', models.IntegerField()),
                ('audio_score', models.IntegerField()),
                ('video_score', models.IntegerField()),
                ('experience_score', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
